name: CI/CD

on:
  push:
    branches:
      - main
      - principal

jobs:
  validar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar Redocly CLI
        run: npm install -g @redocly/cli

      - name: Validar OpenAPI
        run: redocly lint openapi.yaml

  publicar-docs:
    needs: validar
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Instalar Redocly CLI
        run: npm install -g @redocly/cli

      - name: Gerar documentação HTML
        run: redocly build-docs openapi.yaml -o index.html

      - name: Publicar GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
        
